title: Solving for Homelessness
description: From September 2017 through 2019, the Office of Innovation’s i-team worked with individuals and partners across the City of Austin to understand homelessness in Austin from the perspective of people living those experiences. We also examined some of the public and non-profit response systems that are addressing this growing crisis.

Transparency. Education. Engagement.

This website was created to share the i-team’s processes and research, communicate learnings, and provide information on our recommendations and collaborative projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
